export type ShopMasterRow = {
  item_id: string;
  section: string;
  item_type: string;
  display_name: string;
  short_description: string;
  price_monta_coins: string;
  price_free_coins: string;
  currency_type: string;
  availability: string;
  rarity: string;
  is_paid_only: string;
  is_consumable: string;
  grant_type: string;
  grant_value: string;
  asset_id: string;
  current_path: string;
  recommended_w: string;
  recommended_h: string;
  format: string;
  priority: string;
  notes: string;
};

export const SHOP_MASTER_ROWS: ShopMasterRow[] = [
  {
    "item_id": "paid_bg_spring_meadow_01",
    "section": "spring_event",
    "item_type": "background",
    "display_name": "春風の花畑",
    "short_description": "桜と若草がゆれる春イベント背景",
    "price_monta_coins": "500",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "no",
    "grant_type": "background",
    "grant_value": "paid_bg_spring_meadow_01",
    "asset_id": "bg_spring_meadow_01",
    "current_path": "/img/background/bg_spring_meadow_01.png",
    "recommended_w": "1440",
    "recommended_h": "2560",
    "format": "png",
    "priority": "high",
    "notes": "ホームや主要画面に使う縦長背景。GBA風ピクセルRPGの明るい花畑"
  },
  {
    "item_id": "paid_bg_spring_stream_01",
    "section": "spring_event",
    "item_type": "background",
    "display_name": "せせらぎの春小道",
    "short_description": "小川と花びらが流れる春の小道背景",
    "price_monta_coins": "500",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "no",
    "grant_type": "background",
    "grant_value": "paid_bg_spring_stream_01",
    "asset_id": "bg_spring_stream_01",
    "current_path": "/img/background/bg_spring_stream_01.png",
    "recommended_w": "1440",
    "recommended_h": "2560",
    "format": "png",
    "priority": "medium",
    "notes": "少し落ち着いた春背景。夜背景との差別化用"
  },
  {
    "item_id": "paid_frame_clover_01",
    "section": "spring_event",
    "item_type": "frame",
    "display_name": "クローバーフレーム",
    "short_description": "若草色と小さなクローバーのやさしいフレーム",
    "price_monta_coins": "400",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "no",
    "grant_type": "frame",
    "grant_value": "paid_frame_clover_01",
    "asset_id": "frame_clover_01",
    "current_path": "/img/deco_frame/frame_clover_01_aligned_01.png",
    "recommended_w": "960",
    "recommended_h": "640",
    "format": "png",
    "priority": "medium",
    "notes": "春イベントの低彩度グリーン系。ショップ/持ち物でのプレビューにも使う"
  },
  {
    "item_id": "paid_deco_sakura_petals_01",
    "section": "spring_event",
    "item_type": "decoration",
    "display_name": "花びらのかざり",
    "short_description": "ホームにふわっと春感を足す花びらデコ",
    "price_monta_coins": "500",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "normal",
    "is_paid_only": "yes",
    "is_consumable": "no",
    "grant_type": "decoration",
    "grant_value": "paid_deco_sakura_petals_01",
    "asset_id": "deco_sakura_petals_01",
    "current_path": "/img/decoration/deco_sakura_petals_01.png",
    "recommended_w": "1024",
    "recommended_h": "1024",
    "format": "png",
    "priority": "medium",
    "notes": "透過PNG。ホームのモンスター周辺や背景上に重ねる想定"
  },
  {
    "item_id": "paid_deco_picnic_basket_01",
    "section": "spring_event",
    "item_type": "decoration",
    "display_name": "ピクニックバスケット",
    "short_description": "モンスターの横に置ける春の小物デコ",
    "price_monta_coins": "600",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "normal",
    "is_paid_only": "yes",
    "is_consumable": "no",
    "grant_type": "decoration",
    "grant_value": "paid_deco_picnic_basket_01",
    "asset_id": "deco_picnic_basket_01",
    "current_path": "/img/decoration/deco_picnic_basket_01.png",
    "recommended_w": "1024",
    "recommended_h": "1024",
    "format": "png",
    "priority": "medium",
    "notes": "透過PNG。下部に影を含めると置物感が出る"
  },
  {
    "item_id": "paid_deco_flower_lantern_01",
    "section": "spring_event",
    "item_type": "decoration",
    "display_name": "花灯りランタン",
    "short_description": "夜背景にも合う花模様のランタンデコ",
    "price_monta_coins": "500",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "no",
    "grant_type": "decoration",
    "grant_value": "paid_deco_flower_lantern_01",
    "asset_id": "deco_flower_lantern_01",
    "current_path": "/img/decoration/deco_flower_lantern_01.png",
    "recommended_w": "1024",
    "recommended_h": "1024",
    "format": "png",
    "priority": "low",
    "notes": "透過PNG。夜の春イベント演出用"
  },
  {
    "item_id": "paid_spring_egg_01",
    "section": "spring_event",
    "item_type": "event_egg",
    "display_name": "春の芽吹きたまご",
    "short_description": "花模様のたまご。春イベントモンスターに出会える",
    "price_monta_coins": "500",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "yes",
    "grant_type": "event_egg",
    "grant_value": "spring_monster_pool_01",
    "asset_id": "monster_spring_egg_01",
    "current_path": "/img/monster/event_spring_egg_01.png",
    "recommended_w": "1024",
    "recommended_h": "1024",
    "format": "png",
    "priority": "high",
    "notes": "イベントショップで交換する想定の春イベント卵"
  },
  {
    "item_id": "paid_boost_exp_20_1h_01",
    "section": "booster",
    "item_type": "booster",
    "display_name": "EXPブースト 1時間",
    "short_description": "1時間だけ獲得EXPが20%アップ",
    "price_monta_coins": "0",
    "price_free_coins": "100",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "booster",
    "grant_value": "exp_boost_20_1h",
    "asset_id": "icon_boost_exp_20_01",
    "current_path": "/img/icon/icon_boost_exp_20_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "消耗品。重複不可で時間延長のみ推奨"
  },
  {
    "item_id": "paid_boost_exp_20_3h_01",
    "section": "booster",
    "item_type": "booster",
    "display_name": "EXPブースト 3時間",
    "short_description": "3時間だけ獲得EXPが20%アップ",
    "price_monta_coins": "0",
    "price_free_coins": "300",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "booster",
    "grant_value": "exp_boost_20_3h",
    "asset_id": "icon_boost_exp_20_03",
    "current_path": "/img/icon/icon_boost_exp_20_03.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "1時間版より少し割安"
  },
  {
    "item_id": "paid_boost_exp_20_24h_01",
    "section": "booster",
    "item_type": "booster",
    "display_name": "EXPブースト 24時間",
    "short_description": "24時間だけ獲得EXPが20%アップ",
    "price_monta_coins": "100",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "booster",
    "grant_value": "exp_boost_20_24h",
    "asset_id": "icon_boost_exp_20_1day",
    "current_path": "/img/icon/icon_boost_exp_20_1day.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "無料版より長く使える有料版。"
  },
  {
    "item_id": "paid_boost_exp_20_72h_01",
    "section": "booster",
    "item_type": "booster",
    "display_name": "EXPブースト 72時間",
    "short_description": "72時間だけ獲得EXPが20%アップ",
    "price_monta_coins": "300",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "booster",
    "grant_value": "exp_boost_20_72h",
    "asset_id": "icon_boost_exp_20_3day",
    "current_path": "/img/icon/icon_boost_exp_20_3day.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "無料版より長く使える有料版。"
  },
  {
    "item_id": "power_charm_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "ちからのおまもり",
    "short_description": "次の3タスクは Power だけが伸びるおまもりです。",
    "price_monta_coins": "0",
    "price_free_coins": "300",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "power:3",
    "asset_id": "icon_charm_power_free_01",
    "current_path": "/img/item/charm/icon_charm_power_free_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "通常ショップのフリーコイン用おまもり"
  },
  {
    "item_id": "heal_charm_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "いやしのおまもり",
    "short_description": "次の3タスクは Heal だけが伸びるおまもりです。",
    "price_monta_coins": "0",
    "price_free_coins": "300",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "heal:3",
    "asset_id": "icon_charm_heal_free_01",
    "current_path": "/img/item/charm/icon_charm_heal_free_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "通常ショップのフリーコイン用おまもり"
  },
  {
    "item_id": "knowledge_charm_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "ちえのおまもり",
    "short_description": "次の3タスクは Knowledge だけが伸びるおまもりです。",
    "price_monta_coins": "0",
    "price_free_coins": "300",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "knowledge:3",
    "asset_id": "icon_charm_knowledge_free_01",
    "current_path": "/img/item/charm/icon_charm_knowledge_free_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "通常ショップのフリーコイン用おまもり"
  },
  {
    "item_id": "create_charm_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "ひらめきのおまもり",
    "short_description": "次の3タスクは Create だけが伸びるおまもりです。",
    "price_monta_coins": "0",
    "price_free_coins": "300",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "create:3",
    "asset_id": "icon_charm_create_free_01",
    "current_path": "/img/item/charm/icon_charm_create_free_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "medium",
    "notes": "通常ショップのフリーコイン用おまもり"
  },
  {
    "item_id": "paid_charm_power_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "ちからのおまもり+",
    "short_description": "次の10タスクは Power だけが伸びる、モンタコイン用の特別なおまもりです。",
    "price_monta_coins": "300",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "power:10",
    "asset_id": "icon_charm_power_01",
    "current_path": "/img/item/charm/icon_charm_power_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "無料版より長く使える有料版。将来の paid coin 消費先候補"
  },
  {
    "item_id": "paid_charm_heal_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "いやしのおまもり+",
    "short_description": "次の10タスクは Heal だけが伸びる、モンタコイン用の特別なおまもりです。",
    "price_monta_coins": "300",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "heal:10",
    "asset_id": "icon_charm_heal_01",
    "current_path": "/img/item/charm/icon_charm_heal_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "無料版と区別するためアイコンは専用色・専用装飾にする"
  },
  {
    "item_id": "paid_charm_knowledge_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "ちえのおまもり+",
    "short_description": "次の10タスクは Knowledge だけが伸びる、モンタコイン用の特別なおまもりです。",
    "price_monta_coins": "300",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "knowledge:10",
    "asset_id": "icon_charm_knowledge_01",
    "current_path": "/img/item/charm/icon_charm_knowledge_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "無料版より使用回数を増やした有料版の仮案"
  },
  {
    "item_id": "paid_charm_create_01",
    "section": "evergreen",
    "item_type": "charm",
    "display_name": "ひらめきのおまもり+",
    "short_description": "次の10タスクは Create だけが伸びる、モンタコイン用の特別なおまもりです。",
    "price_monta_coins": "300",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "yes",
    "grant_type": "attribute_charm",
    "grant_value": "create:10",
    "asset_id": "icon_charm_create_01",
    "current_path": "/img/item/charm/icon_charm_create_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "無料版と同じ系統だが有料は演出や輪郭を豪華にすると差別化しやすい"
  },
  {
    "item_id": "paid_frame_starlight_01",
    "section": "evergreen",
    "item_type": "frame",
    "display_name": "星灯りフレーム",
    "short_description": "星と青い光の通年販売フレーム",
    "price_monta_coins": "400",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "no",
    "grant_type": "frame",
    "grant_value": "paid_frame_starlight_01",
    "asset_id": "frame_starlight_01",
    "current_path": "/img/deco_frame/frame_starlight_01_aligned_01.png",
    "recommended_w": "960",
    "recommended_h": "640",
    "format": "png",
    "priority": "medium",
    "notes": "春以外の有料ショップ常設品。既存 sky_crystal と被りすぎないよう濃紺寄り"
  },
  {
    "item_id": "paid_bg_library_magic_01",
    "section": "evergreen",
    "item_type": "background",
    "display_name": "まほう書庫の背景",
    "short_description": "図鑑好き向けの静かな魔法書庫背景",
    "price_monta_coins": "0",
    "price_free_coins": "500",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "background",
    "grant_value": "paid_bg_library_magic_01",
    "asset_id": "bg_library_magic_01",
    "current_path": "/img/background/bg_library_magic_01.png",
    "recommended_w": "1440",
    "recommended_h": "2560",
    "format": "png",
    "priority": "medium",
    "notes": "常設背景。図鑑背景との世界観に寄せる"
  },
  {
    "item_id": "paid_bundle_spring_starter_01",
    "section": "spring_event",
    "item_type": "bundle",
    "display_name": "春イベントスターターセット",
    "short_description": "500モンタコイン+春の芽吹きたまご+EXPブースト 24時間",
    "price_monta_coins": "500",
    "price_free_coins": "0",
    "currency_type": "jpy",
    "availability": "event_limited",
    "rarity": "ultra",
    "is_paid_only": "yes",
    "is_consumable": "yes",
    "grant_type": "bundle",
    "grant_value": "paid_coin:500|spring_egg_01|paid_boost_exp_20_24h_01",
    "asset_id": "bundle_spring_starter_01",
    "current_path": "/img/icon/icon_bundle_spring_starter_01.png",
    "recommended_w": "1024",
    "recommended_h": "1024",
    "format": "png",
    "priority": "high",
    "notes": "Stripe Checkoutの決済商品。購入後にモンタコイン500とイベント卵、24時間ブーストを自動付与"
  },
  {
    "item_id": "paid_bundle_spring_deco_01",
    "section": "spring_event",
    "item_type": "bundle",
    "display_name": "春のかざりセット",
    "short_description": "ピクニックバスケット+花灯りランタン+春の芽吹きたまご",
    "price_monta_coins": "500",
    "price_free_coins": "0",
    "currency_type": "paid_coin",
    "availability": "event_limited",
    "rarity": "rare",
    "is_paid_only": "yes",
    "is_consumable": "yes",
    "grant_type": "bundle",
    "grant_value": "deco_picnic_basket_01|deco_flower_lantern_01|spring_egg_01",
    "asset_id": "bundle_spring_deco_01",
    "current_path": "/img/icon/icon_bundle_spring_deco_01.png",
    "recommended_w": "1024",
    "recommended_h": "1024",
    "format": "png",
    "priority": "medium",
    "notes": "イベントショップのモンタコイン交換セット"
  },
  {
    "item_id": "home_night",
    "section": "evergreen",
    "item_type": "background",
    "display_name": "星夜の草原",
    "short_description": "夜の雰囲気が楽しめるホーム背景です。",
    "price_monta_coins": "0",
    "price_free_coins": "500",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "background",
    "grant_value": "home_night",
    "asset_id": "bg_home_night_01",
    "current_path": "/img/background/bg_home_night_01.png",
    "recommended_w": "1440",
    "recommended_h": "2560",
    "format": "png",
    "priority": "medium",
    "notes": "常設の無料コイン背景"
  },
  {
    "item_id": "main_field",
    "section": "evergreen",
    "item_type": "background",
    "display_name": "冒険のフィールド",
    "short_description": "少し広い世界を感じられるホーム背景です。",
    "price_monta_coins": "0",
    "price_free_coins": "500",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "background",
    "grant_value": "main_field",
    "asset_id": "bg_main_field_01",
    "current_path": "/img/background/bg_main_field_01.png",
    "recommended_w": "1440",
    "recommended_h": "2560",
    "format": "png",
    "priority": "medium",
    "notes": "常設の無料コイン背景"
  },
  {
    "item_id": "classic_gold",
    "section": "evergreen",
    "item_type": "frame",
    "display_name": "クラシックフレーム",
    "short_description": "いまの雰囲気をそのまま楽しめる基本フレームです。",
    "price_monta_coins": "0",
    "price_free_coins": "0",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "frame",
    "grant_value": "classic_gold",
    "asset_id": "",
    "current_path": "960",
    "recommended_w": "640",
    "recommended_h": "png",
    "format": "medium",
    "priority": "初期所持の基本フレーム",
    "notes": ""
  },
  {
    "item_id": "sky_crystal",
    "section": "evergreen",
    "item_type": "frame",
    "display_name": "スカイクリスタル",
    "short_description": "青みのある光で、すっきりした印象に変わるフレームです。",
    "price_monta_coins": "0",
    "price_free_coins": "300",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "frame",
    "grant_value": "sky_crystal",
    "asset_id": "",
    "current_path": "960",
    "recommended_w": "640",
    "recommended_h": "png",
    "format": "medium",
    "priority": "常設の無料コインフレーム",
    "notes": ""
  },
  {
    "item_id": "rose_charm",
    "section": "evergreen",
    "item_type": "frame",
    "display_name": "ローズチャーム",
    "short_description": "やさしいピンク系で、少し華やかな雰囲気になるフレームです。",
    "price_monta_coins": "0",
    "price_free_coins": "300",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "frame",
    "grant_value": "rose_charm",
    "asset_id": "",
    "current_path": "960",
    "recommended_w": "640",
    "recommended_h": "png",
    "format": "medium",
    "priority": "常設の無料コインフレーム",
    "notes": ""
  },
  {
    "item_id": "paid_coin_pack_small",
    "section": "coin_pack",
    "item_type": "coin_pack",
    "display_name": "モンタコイン 120枚",
    "short_description": "まず試しやすいいちばん小さなモンタコインパックです。",
    "price_monta_coins": "100",
    "price_free_coins": "0",
    "currency_type": "jpy",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "paid_coin",
    "grant_value": "120",
    "asset_id": "icon_paid_coin_pack_01",
    "current_path": "/img/icon/icon_paid_coin_pack_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "Stripe Checkoutで販売"
  },
  {
    "item_id": "paid_coin_pack_medium",
    "section": "coin_pack",
    "item_type": "coin_pack",
    "display_name": "モンタコイン 380枚",
    "short_description": "少し遊びやすい中サイズのモンタコインパックです。",
    "price_monta_coins": "300",
    "price_free_coins": "0",
    "currency_type": "jpy",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "paid_coin",
    "grant_value": "380",
    "asset_id": "icon_paid_coin_pack_01",
    "current_path": "/img/icon/icon_paid_coin_pack_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "Stripe Checkoutで販売"
  },
  {
    "item_id": "paid_coin_pack_large",
    "section": "coin_pack",
    "item_type": "coin_pack",
    "display_name": "モンタコイン 700枚",
    "short_description": "しっかり使いたい方向けのモンタコインパックです。",
    "price_monta_coins": "600",
    "price_free_coins": "0",
    "currency_type": "jpy",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "paid_coin",
    "grant_value": "700",
    "asset_id": "icon_paid_coin_pack_01",
    "current_path": "/img/icon/icon_paid_coin_pack_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "Stripe Checkoutで販売"
  },
  {
    "item_id": "paid_coin_pack_xlarge",
    "section": "coin_pack",
    "item_type": "coin_pack",
    "display_name": "モンタコイン 1600枚",
    "short_description": "一番お得に使える大容量モンタコインパックです。",
    "price_monta_coins": "1000",
    "price_free_coins": "0",
    "currency_type": "jpy",
    "availability": "always",
    "rarity": "rare",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "paid_coin",
    "grant_value": "1600",
    "asset_id": "icon_paid_coin_pack_01",
    "current_path": "/img/icon/icon_paid_coin_pack_01.png",
    "recommended_w": "512",
    "recommended_h": "512",
    "format": "png",
    "priority": "high",
    "notes": "Stripe Checkoutで販売"
  },
  {
    "item_id": "home_morning",
    "section": "evergreen",
    "item_type": "background",
    "display_name": "はじまりの草原",
    "short_description": "ホームで使える基本背景です。",
    "price_monta_coins": "0",
    "price_free_coins": "0",
    "currency_type": "free_coin",
    "availability": "always",
    "rarity": "normal",
    "is_paid_only": "no",
    "is_consumable": "no",
    "grant_type": "background",
    "grant_value": "home_morning",
    "asset_id": "bg_home_morning_01",
    "current_path": "/img/background/bg_home_morning_01.png",
    "recommended_w": "1440",
    "recommended_h": "2560",
    "format": "png",
    "priority": "medium",
    "notes": "初期所持の基本背景"
  }
] as const;

export const SHOP_MASTER_BY_ID = Object.fromEntries(
  SHOP_MASTER_ROWS.map((row) => [row.item_id, row])
) as Record<string, ShopMasterRow>;
